default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: supermercados_db_dev
  username: postgres
  password: 123456
  host: localhost

test:
  <<: *default
  database: supermercados_db_test
  username: postgres
  password: 123456
  host: localhost

production:
  <<: *default
  database: supermercados_db_production
  username: postgres
  password: 123456
  host: localhost
